# Generated by Django 6.0.3 on 2026-04-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_paid_at_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='participant_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
