# Generated by Django 6.0.3 on 2026-04-06 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.URLField(blank=True)),
                ('rating', models.FloatField(default=5.0)),
                ('reviews', models.IntegerField(default=0)),
            ],
        ),
    ]
