# Generated by Django 6.0.3 on 2026-04-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='max_popple',
            new_name='max_peopple',
        ),
    ]
