# Generated by Django 6.0.3 on 2026-04-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_rename_max_popple_tour_max_peopple'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='max_peopple',
            new_name='max_people',
        ),
    ]
