# Generated by Django 6.0.3 on 2026-04-05 04:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rename_max_peopple_tour_max_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False),
        ),
    ]
