# Generated by Django 6.0.3 on 2026-04-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_category_tour_duration_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='tour_images/'),
        ),
    ]
