# Generated by Django 6.0.3 on 2026-05-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guide_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guide_verification_reason',
            field=models.TextField(blank=True, help_text='Admin notes for rejection'),
        ),
        migrations.AddField(
            model_name='user',
            name='guide_verification_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', help_text="User's guide verification application status", max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='guide_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_guide',
            field=models.BooleanField(default=False, help_text='Admin-approved guide status'),
        ),
    ]
