# Generated by Django 6.0.3 on 2026-05-08 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='2FA is active for this user')),
                ('method', models.CharField(choices=[('totp', 'Time-based One-Time Password (TOTP)'), ('sms', 'SMS-based OTP')], default='totp', max_length=10)),
                ('totp_secret', models.CharField(blank=True, help_text='Base32-encoded TOTP secret', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for SMS OTP', max_length=20)),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='List of one-time backup codes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabled_at', models.DateTimeField(blank=True, help_text='When 2FA was enabled', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Last successful 2FA verification', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two-Factor Authentication',
                'verbose_name_plural': 'Two-Factor Authentications',
                'indexes': [models.Index(fields=['user', 'is_enabled'], name='users_twofa_user_id_2b7ad8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(help_text='Unique session identifier', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.IntegerField(default=0, help_text='Number of failed 2FA attempts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two-Factor Session',
                'verbose_name_plural': 'Two-Factor Sessions',
                'indexes': [models.Index(fields=['session_code'], name='users_twofa_session_28945f_idx'), models.Index(fields=['user', 'verified', 'expires_at'], name='users_twofa_user_id_5587fc_idx')],
            },
        ),
    ]
