# Generated by Django 6.0.3 on 2026-05-10 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_twofactorauth_twofactorsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_passport', 'ID / Passport'), ('certification', 'Tour Guide Certification'), ('insurance', 'Public Liability Insurance'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='guide_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guide Document',
                'verbose_name_plural': 'Guide Documents',
            },
        ),
    ]
